version: '3.8'

services:
  app:
    image: wags_queue
    container_name: wags_queue
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - wags-network

  db:
    image: mysql:8.0
    container_name: wags_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_wags
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - mysql-data:/var/lib/mysql
    networks:
      - wags-network

networks:
  wags-network:
    driver: bridge

volumes:
  mysql-data:
